# Generated by Django 4.1.3 on 2022-12-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='id_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.organisation'),
        ),
    ]
